version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - '/portainer/AppData/Matomo/DB:/bitnami'
  matomo:
    image: 'docker.io/bitnami/matomo:3-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - MATOMO_DATABASE_PASSWORD=${DB_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '8089:80'
      - '8088:443'
    depends_on:
      - mariadb
    volumes:
      - '/portainer/AppData/Matomo/Config:/bitnami'
